Upgrade to sitecore 10.2 (based on PR #150)
Sitecore/MVP-Site pull request #151
Opened 2021-12-01 13:28 UTC by anderslaub

## Description
- Upgraded platform to Sitecore 10.2
- Upgraded to Headless Services v19.0
- Changed name of env var RENDERING_HOST to MVP_RENDERING_HOST as prep for multisite setup
- Added serverSideRenderingEngineApplicationUrl attribute on mvp-site app
- changed depends on for cm/cd to not wait ~5 min for them to start up (mssql-init worst-case service completion time)
- Added mem limits in compose file

k8s specs is NOT UPDATED since I cannot test deployment.

Closes #94 

## Motivation
Preparing to add sugcon site(s)

## How Has This Been Tested?
- Solution builds and publishes in VS 2022
- Containers builds
- Everything works on my machine

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)
- [] Documentation update (non-breaking change; modified files are limited to the `/docs` directory)
- [x] Upgrade (not breaking functionality)

## Checklist:
- [x] I have read the Contributing guide.
- [x] My code follows the code style of this project.
- [x] My code/comments/docs fully adhere to the Code of Conduct.
- [ ] My change is a code change and it requires an update to the documentation.
- [ ] My change is a documentation change and it requires an update to the navigation.

I have not read the docs so I am not aware if these needs updating.

2021-12-01 15:45 UTC, cassidydotdk requested changes

2021-12-01 15:45 UTC, cassidydotdk commented on init.ps1
> +Add-HostsEntry $mvprenderingHost
This fails, since 4 lines above we have this:

```
$renderingHost = "mvp.sc.localhost"
```

This variable needs to be changed as well.

2021-12-01 16:35 UTC, anderslaub commented
@cassidydotdk I had the same exception. For some reason I had to run a Republish - it is missing api key in web db that causes it.

2021-12-02 10:45 UTC, cassidydotdk commented
> Also getting the following, when accessing mvp.sc.local after everything fires up correctly.
> 
> ```
> Sitecore.LayoutService.Client.Exceptions.InvalidResponseSitecoreLayoutServiceClientException: The Sitecore layout service returned a response in an invalid format.
>  ---> Sitecore.LayoutService.Client.Exceptions.SitecoreLayoutServiceServerException: The Sitecore layout service returned a server error.
>    --- End of inner exception stack trace ---
>    at Mvp.Project.MvpSite.Controllers.DefaultController.Index(Route route) in C:\solution\src\Project\MvpSite\rendering\Controllers\DefaultController.cs:line 30
>    at lambda_method(Closure , Object , Object[] )
>    at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Sitecore.AspNet.RenderingEngine.Middleware.RenderingEngineMiddleware.Invoke(HttpContext httpContext, IViewComponentHelper viewComponentHelper, IHtmlHelper htmlHelper)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
>    at Sitecore.AspNet.ExperienceEditor.ExperienceEditorMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
> ```

Resolved by ef28888b85eb7052f7a41b346b2da42be77894f2

2021-12-02 11:02 UTC, cassidydotdk approved these changes

2021-12-07 04:07 UTC, merged