Initial MVP 10.1 Commit
Sitecore/MVP-Site pull request #19
Opened 2021-04-08 07:09 UTC by navancommits

## Description
Changes compatible with Sitecore 10.1

## Motivation
Since Sitecore 10.1 is the latest version, good to keep up with the latest

## How Has This Been Tested?
Just followed the usual process of running init.ps1 and up.ps1 to see the site running locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (non-breaking change; modified files are limited to the `/docs` directory)

## Checklist:

- [x] I have read the Contributing guide.
- [x] My code follows the code style of this project.
- [x] My code/comments/docs fully adhere to the Code of Conduct.
- [x] My change is a code change and it requires an update to the documentation.
- [ ] My change is a documentation change and it requires an update to the navigation.

2021-04-08 07:24 UTC, navancommits commented
https://navansitecorenotes.blogspot.com/2021/04/sitecore-mvp-site-running-on-sitecore.html

2021-04-14 04:01 UTC, robearlam requested changes
Thanks for contributing!

Mostly looks good, but I added some comments to the changes you made to init.ps1.

If you have improvements that can be suggested for that process they should be lodged as a separate PR as they are unrelated to the 10.1 upgrade.

2021-04-14 07:46 UTC, navancommits reviewed
Hi Rob, I wanted to come back to this pr and make it cleaner but you beat me to it! Thanks for the review... This runs fine after the changes....

2021-04-15 00:47 UTC, navancommits commented on init.ps1
> -git update-index --assume-unchanged .env
Done

2021-04-15 00:48 UTC, navancommits commented on init.ps1
> +
Done

2021-04-15 00:48 UTC, navancommits commented on init.ps1
> +
Done

2021-04-15 01:51 UTC, merged